config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get 'dashboard/index'
  resources :supplier_products do
    member do
    post :add_item
    end
  end
  resources :shopkeeper_products do
    member do
    post :add_item
    end
  end
  resources :warehouse_products  do
    member do
    post :add_item
    end
  end
  resources :suppliers
  resources :warehouses 
  resources :users
  resources :categories do
  resources :products
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/owner.rb
class Owner < User
  has_one :warehouse
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :supplier_products
  has_many :suppliers, through: :supplier_products
  has_many :shopkeeper_products
  has_many :shopkeepers,through: :shopkeeper_products
  has_many :warehouse_products
  has_many :warehouses,through: :warehouse_products
  belongs_to :category
end

app/models/shopkeeper.rb
class Shopkeeper < User
	has_many :shopkeeper_products
	has_many :products,through: :shopkeeper_products
end

app/models/shopkeeper_product.rb
class ShopkeeperProduct < ApplicationRecord
	belongs_to :shopkeeper,optional: true
	belongs_to :product,optional: true
end

app/models/supplier.rb
class Supplier < User
  has_many :supplier_products
  has_many :products, through: :supplier_products
end

app/models/supplier_product.rb
class SupplierProduct < ApplicationRecord
	belongs_to :supplier,optional: true
	belongs_to :product,optional: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :warehouse_products
  has_many :products, through: :warehouse_products
end

app/models/warehouse_product.rb
class WarehouseProduct < ApplicationRecord
	belongs_to :warehouse,optional: true
	belongs_to :product,optional: true

  def total_price
    shopkeeper_product = ShopkeeperProduct.find_by(product_id: product.id)
    quantity = shopkeeper_product&.product_quantity || 0
    product.price * quantity + extended_price * quantity
  end
  
  def sold_product
    shopkeeper_product = ShopkeeperProduct.find_by(product_id: product.id)
    quantity = shopkeeper_product&.product_quantity || 0 
  end
  
  def profit_percentage
    shopkeeper_product = ShopkeeperProduct.find_by(product_id: product.id)
    quantity = shopkeeper_product&.product_quantity || 0 
    if quantity > 0
     (extended_price.to_f * 100 /product.price).round(2)
    else
     0
    end
  end

  def profit
    shopkeeper_product = ShopkeeperProduct.find_by(product_id: product.id)
    quantity = shopkeeper_product&.product_quantity || 0
    extended_price * quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @warehouse_products = WarehouseProduct.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/supplier_products_helper.rb
module SupplierProductsHelper
end

app/helpers/warehouse_products_helper.rb
module WarehouseProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<h1 class="text-secondary"><center>Categories</center></h1>
<center><table class="table table-bordered" style="width: 50%">
  <tr>
    <th>Category</th>
    </tr>
    <% @categories.each do |category| %>
  <tr>
    <td class="text-success"><%= category.name %></td>
    </tr>
    <td><%= link_to 'show', category_products_path(category),class: "btn btn-warning" %></td>
    <% end %>
</table></center>
<center><td><%= link_to 'Back', controller: 'dashboard' %></td></center>

app/views/products/index.html.erb
<h1  class="text-secondary"><center>Products</center></h1>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Price</th>
     <th>description</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td class="text-success"><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
      <td><%= button_to 'add_item', add_item_supplier_product_path(product),class: "btn btn-info" %></td>
    </tr>
  <% end %>
    <td><%= link_to 'Back', controller: 'categories' %></td>
</table>